# Generated by Django 2.2.1 on 2019-12-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20191120_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessusers',
            name='hostname',
            field=models.TextField(default='inplanet004-H87-D3H'),
        ),
        migrations.AlterField(
            model_name='databasebackups',
            name='hostname',
            field=models.TextField(blank=True, default='inplanet004-H87-D3H', null=True),
        ),
    ]
