# Generated by Django 2.2.1 on 2020-06-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20191230_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessusers',
            name='hostname',
            field=models.TextField(default='srv-ubuntu-apps'),
        ),
        migrations.AlterField(
            model_name='databasebackups',
            name='hostname',
            field=models.TextField(blank=True, default='srv-ubuntu-apps', null=True),
        ),
    ]
