# Generated by Django 2.2.1 on 2021-10-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_auto_20211013_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessusers',
            name='hostname',
            field=models.TextField(default='DESKTOP-UNSO1D1'),
        ),
        migrations.AlterField(
            model_name='databasebackups',
            name='hostname',
            field=models.TextField(blank=True, default='DESKTOP-UNSO1D1', null=True),
        ),
    ]
