# Generated by Django 2.2.1 on 2020-07-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctaspaypayments',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
