# Generated by Django 2.2.1 on 2020-07-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0002_ctaspaypayments_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['-id'],
            },
        ),
    ]
