# Generated by Django 2.2.1 on 2020-07-04 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0003_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctaspaypayments',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ctaspaypayments',
            name='bank',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ingress.Banks'),
            preserve_default=False,
        ),
    ]
