# Generated by Django 2.2.1 on 2020-07-04 23:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0004_auto_20200704_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctaspaypayments',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='ctaspaypayments',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingress.Banks', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='ctaspaypayments',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='ctaspaypayments',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='ctaspaypayments',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor'),
        ),
    ]
