# Generated by Django 2.2.1 on 2020-07-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0005_auto_20200704_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctaspaypayments',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de cuenta'),
        ),
    ]
