# Generated by Django 2.2.1 on 2020-08-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0006_auto_20200704_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio Unitario'),
        ),
    ]
