# Generated by Django 2.2.1 on 2019-12-30 18:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0009_auto_20191229_1730'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[('', '-----------'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1)),
                ('day', models.IntegerField()),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_assistance_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_assistance_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de finalización')),
                ('rmu', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Person', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ElementsRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('type', models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Egreso')], verbose_name='Tipo')),
                ('calculation', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Porcentaje')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_elementsrol_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_elementsrol_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Elemento del Rol',
                'verbose_name_plural': 'Elementos del Rol',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[('', '-----------'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1)),
                ('dayslab', models.IntegerField(default=0)),
                ('rmu', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('ingress', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('egress', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contracts')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_salary_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_salary_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de Pago',
                'verbose_name_plural': 'Roles de Pago',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ElementsRol')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Salary')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_salarydet_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_salarydet_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salario Det',
                'verbose_name_plural': 'Salarios Det',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_job_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_job_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('', '-------'), ('permiso', 'Permiso'), ('vacacion', 'Vacaciones'), ('otros', 'Otros')], max_length=100)),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de finalización')),
                ('details', models.CharField(blank=True, max_length=500, null=True, verbose_name='Detalles')),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contracts', verbose_name='Empleado')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_events_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_events_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='contracts',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Job', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_contracts_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contracts',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_contracts_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssistanceDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.BooleanField(default=False)),
                ('assist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Assistance')),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contracts')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.Events')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_assistancedet_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_assistancedet_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia Det',
                'verbose_name_plural': 'Asistencias Det',
                'ordering': ['-id'],
            },
        ),
    ]
