# Generated by Django 2.2.1 on 2019-12-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('', '-------'), ('permiso', 'Permiso'), ('vacacion', 'Vacaciones'), ('otros', 'Otros')], max_length=100, verbose_name='Tipo'),
        ),
    ]
