# Generated by Django 2.2.1 on 2020-08-18 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_auto_20200817_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistancedet',
            old_name='time',
            new_name='hour',
        ),
    ]
