# Generated by Django 2.2.1 on 2019-12-28 19:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Period')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Person')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_teachermatter_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_teachermatter_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente Materia',
                'verbose_name_plural': 'Docente Materias',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherMatterDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('course_mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.CourseMat')),
                ('horary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.TeacherMatter')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_teachermatterdet_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_teachermatterdet_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente Curso Det',
                'verbose_name_plural': 'Docente Cursos Det',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='teacherhorarydet',
            name='course_mat',
        ),
        migrations.RemoveField(
            model_name='teacherhorarydet',
            name='horary',
        ),
        migrations.RemoveField(
            model_name='teacherhorarydet',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='teacherhorarydet',
            name='user_updated',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='teach_cours_mat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.TeacherMatterDet'),
        ),
        migrations.DeleteModel(
            name='TeacherHorary',
        ),
        migrations.DeleteModel(
            name='TeacherHoraryDet',
        ),
    ]
