# Generated by Django 2.2.1 on 2019-12-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20191228_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachermatterdet',
            old_name='horary',
            new_name='teacher_mat',
        ),
    ]
