# Generated by Django 2.2.1 on 2019-12-29 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20191229_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='college.ClassRoom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
