# Generated by Django 2.2.1 on 2019-12-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_auto_20191229_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculation',
            name='state',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('proceso', 'En proceso'), ('rechazado', 'Rechazado')], default='proceso', max_length=50),
        ),
    ]
