# Generated by Django 2.2.1 on 2019-12-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_matriculation_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='student',
        ),
        migrations.AddField(
            model_name='notes',
            name='matr',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='college.Matriculation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='obs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='partial',
            field=models.CharField(choices=[('primero', 'Primer Parcial'), ('segundo', 'Segundo Parcial'), ('tercero', 'Tercer Parcial')], default='primero', max_length=20),
        ),
    ]
