# Generated by Django 2.2.1 on 2019-12-29 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_auto_20191229_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='obs',
        ),
        migrations.AddField(
            model_name='notes',
            name='calif',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='notes',
            name='partial',
            field=models.CharField(choices=[('primero', 'Primer Parcial'), ('segundo', 'Segundo Parcial'), ('tercero', 'Tercer Parcial')], default='primero', max_length=20),
        ),
        migrations.AddField(
            model_name='notes',
            name='teach_cours_mat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='college.TeacherMatterDet'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
