# Generated by Django 2.2.1 on 2020-07-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_auto_20200705_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Quimestral 1'), (2, 'Quimestral 2')], default=1),
        ),
        migrations.AlterField(
            model_name='notes',
            name='partial',
            field=models.CharField(choices=[('primero', 'Primer Parcial'), ('segundo', 'Segundo Parcial'), ('tercero', 'Tercer Parcial'), ('examen', 'Examen')], default='primero', max_length=20),
        ),
    ]
