# Generated by Django 2.2.1 on 2021-09-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_classroom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='duration',
            field=models.CharField(default=1, max_length=150, verbose_name='Duración'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='platform_infrastructure',
            field=models.CharField(default=1, max_length=150, verbose_name='Plataforma/Infraestructura'),
            preserve_default=False,
        ),
    ]
