# Generated by Django 2.2.1 on 2021-09-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_auto_20210910_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='duration',
            field=models.IntegerField(max_length=150, verbose_name='Horas de Duración'),
        ),
    ]
