# Generated by Django 2.2.1 on 2021-09-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_auto_20210910_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='platform_infrastructure',
            field=models.CharField(max_length=150, verbose_name='Plataformas'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(1, 'Corta Duración'), (2, 'Larga Duración')], default=1),
        ),
        migrations.AlterField(
            model_name='notes',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Final')], default=1),
        ),
    ]
