# Generated by Django 2.2.1 on 2021-09-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_auto_20210915_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cpay',
            field=models.FileField(blank=True, null=True, upload_to='cpay/%Y/%m/%d'),
        ),
    ]
