# Generated by Django 2.2.1 on 2021-09-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0016_person_cpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='conventional',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Convencional'),
        ),
    ]
