# Generated by Django 2.2.1 on 2021-09-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_auto_20210923_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='conventional',
        ),
    ]
