# Generated by Django 2.2.1 on 2021-10-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0019_auto_20210923_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='calif',
            new_name='average',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='partial',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='semester',
        ),
        migrations.AddField(
            model_name='notes',
            name='exam',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='notes',
            name='lesson1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='notes',
            name='lesson2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='notes',
            name='lesson3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='notes',
            name='lesson4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='duration',
            field=models.IntegerField(verbose_name='Horas de Duración'),
        ),
    ]
