# Generated by Django 2.2.1 on 2021-10-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0020_auto_20211013_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to='course/%Y/%m/%d'),
        ),
    ]
