# Generated by Django 2.2.1 on 2021-10-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0021_course_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='archive',
        ),
        migrations.AddField(
            model_name='classroom',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to='course/%Y/%m/%d'),
        ),
    ]
