# Generated by Django 2.2.1 on 2021-10-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0023_auto_20211018_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='credits',
            field=models.IntegerField(default=1, verbose_name='Horas de materia'),
            preserve_default=False,
        ),
    ]
